[project]
name = "helloshiny"
r_version = "4.6"

# A list of repositories to fetch packages from. Order matters: we will try to get a package from each repository in order.
# The alias is only used in this file if you want to specifically require a dependency to come from a certain repository.
repositories = [
    {alias = "CRAN", url = "https://cloud.r-project.org/"},
]

# A list of packages to install and any additional configuration
dependencies = [
    "dplyr",
    "shiny",
    "readr",
    "shinytest2",
    "ggplot2",
    "plotly",
    "DT",
    "tidyselect",
    "testthat",
]
